name: App Build and Deploy

on:
  push:
    branches: 
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Deploy to Firebase 
      uses: w9jds/firebase-action@v1.0
      with:
        args: deploy --only hosting 
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: kvis-science-fair
